create database CustomDB;

USE CustomDB;

CREATE TABLE CUSTOMERS(
	ID INT not null,
	NAME VARCHAR(15) NOT NULL,
	AGE INT NOT NULL,
	ADDRESS VARCHAR(25),
	SALARY DECIMAL(10,4),
	PRIMARY KEY(ID)
);

CREATE INDEX idx_name ON CUSTOMERS(NAME);

CREATE INDEX idx_name_age ON CUSTOMERS(NAME,age);

SHOW INDEX FROM CUSTOMERS;

CREATE UNIQUE INDEX idx_address_unique ON CUSTOMERS(ADDRESS);

INSERT INTO CUSTOMERS 
VALUES
(1,'Test',28,'Delhi',5000);

DROP INDEX idx_name ON CUSTOMERS;

DROP INDEX idx_name_age ON CUSTOMERS;


SHOW INDEX FROM CUSTOMERS;
